targets:
  $default:

    # Reducing sources makes the build slightly faster (some of these are required
    # to exist in the default target).
    sources:
      - lib/**
      - web/**
      - pubspec.yaml
      - lib/$lib$
      - $package$
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules: [fts5]
          # This allows us to share a drift database across isolates (or different tabs on the web)
          generate_connect_constructor: true
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
          new_sql_code_generation: true
          scoped_dart_components: true
          compact_query_methods: true
          named_parameters: true
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        options:
          compiler: dart2js
        dev_options:
          dart2js_args:
            - --no-minify
        release_options:
          dart2js_args:
            - -O4