targets:
  $default:

    # Reducing sources makes the build slightly faster (some of these are required
    # to exist in the default target).
    sources:
      - lib/**
      - web/**
      - pubspec.yaml
      - lib/$lib$
      - $package$
    builders:
      json_serializable|json_serializable:
        generate_for:
          - "lib/**/**.dart"
          - "packages/**/**.dart"
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules: [fts5]
          apply_converters_on_variables: true
          generate_values_in_copy_with: true
          scoped_dart_components: true
          named_parameters: true
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        options:
          compiler: dart2js
        dev_options:
          dart2js_args:
            - --no-minify
        release_options:
          dart2js_args:
            - -O4