name: users_api
description: A dart API client for the Jellyfin User API
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  dio: ^5.7.0
  jellyflut_models:
    path: ../jellyflut_models
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
