name: remote_downloads_api
description: The interface and models for remote downloads API
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  dio: ^5.7.0
  rxdart: ^0.28.0

dev_dependencies:
  pedantic: ^1.11.1
