name: remote_downloads_api
description: The interface and models for remote downloads API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  rxdart: ^0.27.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  pedantic: ^1.11.1
