name: authentication_api
description: A dart API client for the Auth API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.4
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  pedantic: ^1.11.1
  test: ^1.19.2
