name: authentication_repository
description: A repository that handles auth related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_api:
    path: ../authentication_api
  drift: ^1.7.1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  shared_preferences: ^2.0.15
  sqlite_database:
    path: ../sqlite_database

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.4
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  pedantic: ^1.11.1
  test: ^1.19.2
