name: database_downloads_api
description: A Flutter implementation of the DownloadApi that uses local sqlite.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  downloads_api:
    path: ../downloads_api
  jellyflut_models:
    path: ../jellyflut_models
  sqlite_database:
    path: ../sqlite_database
  json_annotation: ^4.9.0
  meta: 1.15.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
