name: downloads_repository
description: A repository that handles downloads related requests.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0-0
  
resolution: workspace

dependencies:
  authentication_repository:
    path: ../authentication_repository
  dio: ^5.9.0
  downloads_api:
    path: ../downloads_api
  drift: ^2.3.0
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.5.0
  path_provider: ^2.0.11
  permission_handler: ^12.0.1
  remote_downloads_api:
    path: ../remote_downloads_api
  rxdart: ^0.28.0
  sqlite_database:
    path: ../sqlite_database

dev_dependencies:
  mocktail: ^0.3.0
