name: music_player_api
description: A dart API client for the music player API
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.4
  items_repository:
    path: ../items_repository
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.9.0
  just_audio_media_kit: ^2.0.6
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5 
  rxdart: ^0.28.0
  sqlite_database:
    path: ../sqlite_database

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  pedantic: ^1.11.1
