name: music_player_api
description: A dart API client for the music player API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_vlc:
      git:
        url: https://github.com/erikas-taroza/dart_vlc.git # Url to the repository
        ref: e661980
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  items_repository:
    path: ../items_repository
  jellyflut_models:
    path: ../jellyflut_models
  sqlite_database:
    path: ../sqlite_database
  json_annotation: ^4.6.0
  just_audio: ^0.9.27
  rxdart: ^0.27.4

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  json_serializable: ^6.2.0
  pedantic: ^1.11.1
  test: ^1.21.7
