name: music_player_api
description: A dart API client for the music player API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  jellyflut_models:
    path: ../jellyflut_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1