name: music_player_repository
description: A repository that handle music player
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  jellyflut_models:
    path: ../jellyflut_models
  music_player_api:
    path: ../music_player_api
  rxdart: ^0.28.0
  sqlite_database:
    path: ../sqlite_database

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
