name: sqlite_database
description: SQlite database to store need content
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  drift: ^2.22.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  http: ^1.2.2
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.9.0
  meta: 1.15.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11
  drift_dev: ^2.22.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
