name: sqlite_database
description: SQlite database to store need content
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.13.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.1.0
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.8.1
  meta: ^1.7.0
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.6
  drift_dev: ^2.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
