name: sqlite_database
description: SQlite database to store need content
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  drift: ^2.3.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  http: ^0.13.5
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.7.0
  meta: ^1.8.0
  path_provider: ^2.0.11
  rxdart: ^0.27.7
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  drift_dev: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
