name: jellyfin_downloads_api
description: A dart API client to download files from Jellyfin API
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  remote_downloads_api:
    path: ../remote_downloads_api
  rxdart: ^0.28.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
