name: jellyfin_downloads_api
description: A dart API client to download files from Jellyfin API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  remote_downloads_api:
    path: ../remote_downloads_api
  rxdart: ^0.27.5
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
