name: jellyfin_authentication_api
description: A dart API client for the Jellyfin Auth API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  authentication_api:
    path: ../authentication_api
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  pedantic: ^1.11.1
  freezed: ^2.0.4
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
