name: jellyfin_authentication_api
description: A dart API client for the Jellyfin Auth API
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  authentication_api:
    path: ../authentication_api
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.1
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.2.0
  pedantic: ^1.11.1
