name: jellyfin_authentication_api
description: A dart API client for the Jellyfin Auth API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_api:
    path: ../authentication_api
  device_info_plus: ^8.0.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  package_info_plus: ^3.0.1
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.0.4
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  pedantic: ^1.11.1
  test: ^1.19.2
