name: jellyfin_authentication_api
description: A dart API client for the Jellyfin Auth API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0-0
  
resolution: workspace

dependencies:
  authentication_api:
    path: ../authentication_api
  device_info_plus: ^12.1.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.7.0
  package_info_plus: ^9.0.0
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^3.2.3
  json_serializable: ^6.2.0
  pedantic: ^1.11.1
