// To parse this JSON data, do
//
//     final media = itemFromMap(jsonString);

import 'package:freezed_annotation/freezed_annotation.dart';

import '../enum/index.dart';
import 'index.dart';

part 'item.freezed.dart';
part 'item.g.dart';

@Freezed()
class Item with _$Item {
  const Item._();

  const factory Item({
    required String id,
    String? originalTitle,
    String? name,
    String? serverId,
    String? etag,
    String? sourceType,
    String? playlistItemId,
    DateTime? dateCreated,
    DateTime? dateLastMediaAdded,
    String? extraType,
    int? airsBeforeSeasonNumber,
    int? airsAfterSeasonNumber,
    int? airsBeforeEpisodeNumber,
    bool? canDelete,
    bool? canDownload,
    bool? hasSubtitles,
    String? preferredMetadataLanguage,
    String? preferredMetadataCountryCode,
    bool? supportsSync,
    String? container,
    String? sortName,
    String? forcedSortName,
    Video3DFormat? video3DFormat,
    DateTime? premiereDate,
    @Default(<ExternalUrl>[]) List<ExternalUrl> externalUrls,
    @Default(<MediaSource>[]) List<MediaSource> mediaSources,
    int? criticRating,
    @Default(<String>[]) List<String> productionLocations,
    String? path,
    bool? enableMediaSourceDisplay,
    String? officialRating,
    String? customRating,
    String? channelId,
    String? channelName,
    String? overview,
    @Default(<String>[]) List<String> taglines,
    @Default(<String>[]) List<String> genres,
    double? communityRating,
    double? cumulativeRunTimeTicks,
    double? runTimeTicks,
    PlayAccess? playAccess,
    String? aspectRatio,
    int? productionYear,
    bool? isPlaceHolder,
    String? number,
    String? channelNumber,
    int? indexNumber,
    int? indexNumberEnd,
    int? parentIndexNumber,
    @Default(<MediaUrl>[]) List<MediaUrl> remoteTrailers,
    @Default(<String, String>{}) Map<String, String> providerIds,
    bool? isHD,
    bool? isFolder,
    String? parentId,
    required ItemType type,
    @Default(<People>[]) List<People> people,
    @Default(<NamedGuidPair>[]) List<NamedGuidPair> studios,
    @Default(<NamedGuidPair>[]) List<NamedGuidPair> genreItems,
    String? parentLogoItemId,
    String? parentBackdropItemId,
    @Default(<String>[]) List<String> parentBackdropImageTags,
    int? localTrailerCount,
    UserData? userData,
    int? recursiveItemCount,
    int? childCount,
    String? seriesName,
    String? seriesId,
    String? seasonId,
    int? specialFeatureCount,
    String? displayPreferencesId,
    String? status,
    String? airTime,
    @Default(<DayOfWeek>[]) List<DayOfWeek> airDays,
    @Default(<String>[]) List<String> tags,
    double? primaryImageAspectRatio,
    @Default(<String>[]) List<String> artists,
    @Default(<NamedGuidPair>[]) List<NamedGuidPair> artistItems,
    String? album,
    CollectionType? collectionType,
    String? displayOrder,
    String? albumId,
    String? albumPrimaryImageTag,
    String? seriesPrimaryImageTag,
    String? albumArtist,
    @Default(<NamedGuidPair>[]) List<NamedGuidPair> albumArtists,
    String? seasonName,
    @Default(<MediaStream>[]) List<MediaStream> mediaStreams,
    VideoType? videoType,
    int? partCount,
    int? mediaSourceCount,
    @Default(<String, String>{}) Map<String, String> imageTags,
    @Default(<String>[]) List<String> backdropImageTags,
    @Default(<String>[]) List<String> screenshotImageTags,
    String? parentLogoImageTag,
    String? parentArtItemId,
    String? parentArtImageTag,
    String? seriesThumbImageTag,
    ImageBlurHashes? imageBlurHashes,
    String? seriesStudio,
    String? parentThumbItemId,
    String? parentThumbImageTag,
    String? parentPrimaryImageItemId,
    String? parentPrimaryImageTag,
    @Default(<Chapter>[]) List<Chapter> chapters,
    LocationType? locationType,
    IsoType? isoType,
    String? mediaType,
    DateTime? endDate,
    @Default(<MetaDataField>[]) List<MetaDataField> lockedFields,
    int? trailerCount,
    int? movieCount,
    int? seriesCount,
    int? programCount,
    int? episodeCount,
    int? songCount,
    int? albumCount,
    int? artistCount,
    int? musicVideoCount,
    bool? lockData,
    int? width,
    int? height,
    String? cameraMake,
    String? cameraModel,
    String? software,
    int? exposureTime,
    int? focalLength,
    String? imageOrientation,
    int? aperture,
    int? shutterSpeed,
    int? latitude,
    int? longitude,
    int? altitude,
    int? isoSpeedRating,
    String? seriesTimerId,
    String? programId,
    String? channelPrimaryImageTag,
    DateTime? startDate,
    int? completionPercentage,
    bool? isRepeat,
    String? episodeTitle,
    ChannelType? channelType,
    Audio? audio,
    bool? isMovie,
    bool? isSports,
    bool? isSeries,
    bool? isLive,
    bool? isNews,
    bool? isKids,
    bool? isPremiere,
    String? timerId,
    String? currentProgram,
  }) = _Item;

  factory Item.fromJson(Map<String, Object?> json) => _$ItemFromJson(json);

  static const empty = Item(id: 'id_that_do_not_exist', type: ItemType.Folder);

  /// Convenience getter to determine whether the current item is empty.
  bool get isEmpty => this == Item.empty;

  /// Convenience getter to determine whether the current item is not empty.
  bool get isNotEmpty => this != Item.empty;
}
