enum FieldsEnum {
  AIRDAYS('airDays'),
  AIRTIME('airTime'),
  AIRSAFTERSEASONNUMBER('airsAfterSeasonNumber'),
  AIRSBEFOREEPISODENUMBER('airsBeforeEpisodeNumber'),
  AIRSBEFORESEASONNUMBER('airsBeforeSeasonNumber'),
  ALBUM('album'),
  ALBUMARTISTS('albumArtists'),
  ARTISTITEMS('artistItems'),
  ASPECTRATIO('aspectRatio'),
  BACKGROUNDCOLOR('backgroundColor'),
  COMMUNITYRATING('communityRating'),
  CRITICRATING('criticRating'),
  CUSTOMRATING('customRating'),
  DATEADDED('dateAdded'),
  DATECREATED('dateCreated'),
  DISPLAYORDER('displayOrder'),
  ENDDATE('endDate'),
  FONTSIZE('forcedSortName'),
  FONTCOLOR('fontSize'),
  FORCEDSORTNAME('fontColor'),
  GENRES('genres'),
  GENREITEMS('genreItems'),
  ID('id'),
  INDEXNUMBER('indexNumber'),
  LOCKDATA('lockData'),
  LOCKEDFIELDS('lockedFields'),
  NAME('name'),
  OFFICIALRATING('officialRating'),
  ORIGINALTITLE('originalTitle'),
  OVERVIEW('overview'),
  PARENTINDEXNUMBER('parentIndexNumber'),
  PEOPLE('people'),
  PREFERREDMETADATACOUNTRYCODE('preferredMetadataCountryCode'),
  PREFERREDMETADATALANGUAGE('preferredMetadataLanguage'),
  PREMIEREDATE('premiereDate'),
  PRODUCTIONYEAR('productionYear'),
  PROVIDERIDS('providerIds'),
  STATUS('status'),
  STUDIOS('studios'),
  TAGLINES('taglines'),
  TAGS('tags'),
  VIDEO3DFORMAT('video3DFormat');

  final String name;

  const FieldsEnum(this.name);
}
