import 'package:jellyflut/models/enum/enum_values.dart';

enum FieldsEnum {
  AIRDAYS,
  AIRTIME,
  AIRSAFTERSEASONNUMBER,
  AIRSBEFOREEPISODENUMBER,
  AIRSBEFORESEASONNUMBER,
  ALBUM,
  ALBUMARTISTS,
  ARTISTITEMS,
  ASPECTRATIO,
  COMMUNITYRATING,
  CRITICRATING,
  CUSTOMRATING,
  DATEADDED,
  DATECREATED,
  DISPLAYORDER,
  ENDDATE,
  FORCEDSORTNAME,
  GENRES,
  ID,
  INDEXNUMBER,
  LOCKDATA,
  LOCKEDFIELDS,
  NAME,
  OFFICIALRATING,
  ORIGINALTITLE,
  OVERVIEW,
  PARENTINDEXNUMBER,
  PEOPLE,
  PREFERREDMETADATACOUNTRYCODE,
  PREFERREDMETADATALANGUAGE,
  PREMIEREDATE,
  PRODUCTIONYEAR,
  PROVIDERIDS,
  STATUS,
  STUDIOS,
  TAGLINES,
  TAGS,
  VIDEO3DFORMAT,
}

final fieldsEnumValues = EnumValues({
  'AirDays': FieldsEnum.AIRDAYS,
  'AirTime': FieldsEnum.AIRTIME,
  'AirsAfterSeasonNumber': FieldsEnum.AIRSAFTERSEASONNUMBER,
  'AirsBeforeEpisodeNumber': FieldsEnum.AIRSBEFOREEPISODENUMBER,
  'AirsBeforeSeasonNumber': FieldsEnum.AIRSBEFORESEASONNUMBER,
  'Album': FieldsEnum.ALBUM,
  'AlbumArtists': FieldsEnum.ALBUMARTISTS,
  'ArtistItems': FieldsEnum.ARTISTITEMS,
  'AspectRatio': FieldsEnum.ASPECTRATIO,
  'CommunityRating': FieldsEnum.COMMUNITYRATING,
  'CriticRating': FieldsEnum.CRITICRATING,
  'CustomRating': FieldsEnum.CUSTOMRATING,
  'DateAdded': FieldsEnum.DATEADDED,
  'DateCreated': FieldsEnum.DATECREATED,
  'DisplayOrder': FieldsEnum.DISPLAYORDER,
  'EndDate': FieldsEnum.ENDDATE,
  'ForcedSortName': FieldsEnum.FORCEDSORTNAME,
  'Genres': FieldsEnum.GENRES,
  'Id': FieldsEnum.ID,
  'IndexNumber': FieldsEnum.INDEXNUMBER,
  'LockData': FieldsEnum.LOCKDATA,
  'LockedFields': FieldsEnum.LOCKEDFIELDS,
  'Name': FieldsEnum.NAME,
  'OfficialRating': FieldsEnum.OFFICIALRATING,
  'OriginalTitle': FieldsEnum.ORIGINALTITLE,
  'Overview': FieldsEnum.OVERVIEW,
  'ParentIndexNumber': FieldsEnum.PARENTINDEXNUMBER,
  'People': FieldsEnum.PEOPLE,
  'PreferredMetadataCountryCode': FieldsEnum.PREFERREDMETADATACOUNTRYCODE,
  'PreferredMetadataLanguage': FieldsEnum.PREFERREDMETADATALANGUAGE,
  'PremiereDate': FieldsEnum.PREMIEREDATE,
  'ProductionYear': FieldsEnum.PRODUCTIONYEAR,
  'ProviderIds': FieldsEnum.PROVIDERIDS,
  'Status': FieldsEnum.STATUS,
  'Studios': FieldsEnum.STUDIOS,
  'Taglines': FieldsEnum.TAGLINES,
  'Tags': FieldsEnum.TAGS,
  'Video3DFormat': FieldsEnum.VIDEO3DFORMAT,
});
