import 'package:jellyflut/models/enum/enum_values.dart';

enum FieldsEnum {
  AIRDAYS,
  AIRTIME,
  AIRSAFTERSEASONNUMBER,
  AIRSBEFOREEPISODENUMBER,
  AIRSBEFORESEASONNUMBER,
  ALBUM,
  ALBUMARTISTS,
  ARTISTITEMS,
  ASPECTRATIO,
  BACKGROUNDCOLOR,
  COMMUNITYRATING,
  CRITICRATING,
  CUSTOMRATING,
  DATEADDED,
  DATECREATED,
  DISPLAYORDER,
  ENDDATE,
  FONTSIZE,
  FONTCOLOR,
  FORCEDSORTNAME,
  GENRES,
  GENREITEMS,
  ID,
  INDEXNUMBER,
  LOCKDATA,
  LOCKEDFIELDS,
  NAME,
  OFFICIALRATING,
  ORIGINALTITLE,
  OVERVIEW,
  PARENTINDEXNUMBER,
  PEOPLE,
  PREFERREDMETADATACOUNTRYCODE,
  PREFERREDMETADATALANGUAGE,
  PREMIEREDATE,
  PRODUCTIONYEAR,
  PROVIDERIDS,
  STATUS,
  STUDIOS,
  TAGLINES,
  TAGS,
  VIDEO3DFORMAT,
}

final fieldsEnumValues = EnumValues({
  'airDays': FieldsEnum.AIRDAYS,
  'airTime': FieldsEnum.AIRTIME,
  'airsAfterSeasonNumber': FieldsEnum.AIRSAFTERSEASONNUMBER,
  'airsBeforeEpisodeNumber': FieldsEnum.AIRSBEFOREEPISODENUMBER,
  'airsBeforeSeasonNumber': FieldsEnum.AIRSBEFORESEASONNUMBER,
  'album': FieldsEnum.ALBUM,
  'albumArtists': FieldsEnum.ALBUMARTISTS,
  'artistItems': FieldsEnum.ARTISTITEMS,
  'aspectRatio': FieldsEnum.ASPECTRATIO,
  'backgroundColor': FieldsEnum.BACKGROUNDCOLOR,
  'communityRating': FieldsEnum.COMMUNITYRATING,
  'criticRating': FieldsEnum.CRITICRATING,
  'customRating': FieldsEnum.CUSTOMRATING,
  'dateAdded': FieldsEnum.DATEADDED,
  'dateCreated': FieldsEnum.DATECREATED,
  'displayOrder': FieldsEnum.DISPLAYORDER,
  'endDate': FieldsEnum.ENDDATE,
  'forcedSortName': FieldsEnum.FORCEDSORTNAME,
  'fontSize': FieldsEnum.FONTSIZE,
  'fontColor': FieldsEnum.FONTCOLOR,
  'genres': FieldsEnum.GENRES,
  'genreItems': FieldsEnum.GENREITEMS,
  'id': FieldsEnum.ID,
  'indexNumber': FieldsEnum.INDEXNUMBER,
  'lockData': FieldsEnum.LOCKDATA,
  'lockedFields': FieldsEnum.LOCKEDFIELDS,
  'name': FieldsEnum.NAME,
  'officialRating': FieldsEnum.OFFICIALRATING,
  'originalTitle': FieldsEnum.ORIGINALTITLE,
  'overview': FieldsEnum.OVERVIEW,
  'parentIndexNumber': FieldsEnum.PARENTINDEXNUMBER,
  'people': FieldsEnum.PEOPLE,
  'preferredMetadataCountryCode': FieldsEnum.PREFERREDMETADATACOUNTRYCODE,
  'preferredMetadataLanguage': FieldsEnum.PREFERREDMETADATALANGUAGE,
  'premiereDate': FieldsEnum.PREMIEREDATE,
  'productionYear': FieldsEnum.PRODUCTIONYEAR,
  'providerIds': FieldsEnum.PROVIDERIDS,
  'status': FieldsEnum.STATUS,
  'studios': FieldsEnum.STUDIOS,
  'taglines': FieldsEnum.TAGLINES,
  'tags': FieldsEnum.TAGS,
  'video3DFormat': FieldsEnum.VIDEO3DFORMAT,
});
