import 'package:authentication_repository/authentication_repository.dart';
import 'package:auto_route/auto_route.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_colorpicker/flutter_colorpicker.dart';
import 'package:flutter_settings_ui/flutter_settings_ui.dart';
import 'package:jellyflut/components/locale_button_selector.dart';
import 'package:jellyflut/providers/theme/theme_provider.dart';
import 'package:jellyflut/routes/router.gr.dart' as r;
import 'package:jellyflut/screens/auth/bloc/auth_bloc.dart';
import 'package:jellyflut/screens/details/template/components/user_icon.dart';
import 'package:jellyflut/screens/settings/components/details_contrast_switch.dart';
import 'package:jellyflut/screens/settings/components/direct_play_switch.dart';
import 'package:jellyflut_models/jellyflut_models.dart';
import 'package:provider/provider.dart';
import 'package:rxdart/subjects.dart';
import 'package:settings_repository/settings_repository.dart';

import '../bloc/settings_bloc.dart';

part 'account_section.dart';
part 'audio_bitrate_value_editor.dart';
part 'audio_player_section.dart';
part 'download_path_section.dart';
part 'infos_section.dart';
part 'interface_section.dart';
part 'theme_switcher_section.dart';
part 'transcode_codec_popup_button.dart';
part 'video_bitrate_value_editor.dart';
part 'video_player_popup_button.dart';
part 'video_player_section.dart';
