name: settings_repository
description: A repository that handles settings related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqlite_database:
    path: ../sqlite_database
  authentication_repository:
    path: ../authentication_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
