name: streaming_api
description: A dart API client for the Jellyfin Streaming API
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  jellyflut_models:
    path: ../jellyflut_models
  sqlite_database:
    path: ../sqlite_database
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  pedantic: ^1.11.1
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
