name: streaming_repository
description: A repository that handles streaming related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_repository:
    path: ../authentication_repository
  better_player: ^0.0.83
  dart_vlc: ^0.4.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_vlc_player: ^7.1.5
  freezed_annotation: ^2.0.3
  items_api:
    path: ../items_api
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.6.0
  sqlite_database:
    path: ../sqlite_database
  streaming_api:
    path: ../streaming_api
  video_player: ^2.4.10
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit
      ref: main
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit_video
      ref: main
  media_kit_libs_windows_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit_libs_windows_video
      ref: main
  media_kit_libs_linux:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      path: media_kit_libs_linux
      ref: main
  window_manager: ^0.2.8
  youtube_explode_dart: ^1.12.3

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.0.4
  json_serializable: ^6.2.0
  pedantic: ^1.11.1
