name: streaming_repository
description: A repository that handles streaming related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  authentication_repository:
    path: ../authentication_repository
  dio: ^5.7.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  items_api:
    path: ../items_api
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.9.0
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  sqlite_database:
    path: ../sqlite_database
  streaming_api:
    path: ../streaming_api
  window_manager: ^0.4.3
  youtube_explode_dart: ^2.3.6

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  pedantic: ^1.11.1
