name: streaming_repository
description: A repository that handles streaming related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  authentication_repository:
    path: ../authentication_repository
  dio: ^4.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  items_api:
    path: ../items_api
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.6.0
  media_kit: ^1.1.10+1
  media_kit_libs_android_video: ^1.1.1
  media_kit_libs_ios_video: ^1.0.4
  media_kit_libs_linux: ^1.0.2
  media_kit_libs_macos_video: ^1.0.5
  media_kit_libs_windows_video: ^1.0.2
  media_kit_video: ^1.2.4
  sqlite_database:
    path: ../sqlite_database
  streaming_api:
    path: ../streaming_api
  video_player: ^2.7.2
  window_manager: ^0.3.7
  youtube_explode_dart: ^2.0.2

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.0.4
  json_serializable: ^6.2.0
  pedantic: ^1.11.1
