name: streaming_repository
description: A repository that handles streaming related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_repository:
    path: ../authentication_repository
  better_player: ^0.0.83
  dart_vlc: ^0.4.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_vlc_player: ^7.2.0
  freezed_annotation: ^2.0.3
  items_api:
    path: ../items_api
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.6.0
  media_kit: ^0.0.11                             # Primary package.
  media_kit_video: ^0.0.12                       # For video rendering.
  media_kit_libs_android_video: ^1.0.6           # Android package for video native libraries.
  media_kit_libs_ios_video: ^1.0.4               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.0.5             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.2           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
  sqlite_database:
    path: ../sqlite_database
  streaming_api:
    path: ../streaming_api
  video_player: ^2.6.1
  window_manager: ^0.3.4
  youtube_explode_dart: ^1.12.4

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.0.4
  json_serializable: ^6.2.0
  pedantic: ^1.11.1
