name: downloads_api
description: The interface and models for an API providing access to downloads.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.9.0
  meta: 1.15.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
