name: downloads_api
description: The interface and models for an API providing access to downloads.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  jellyflut_models:
    path: ../jellyflut_models
  json_annotation: ^4.5.0
  meta: ^1.7.0
  rxdart: ^0.27.4

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  test: ^1.21.7
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
