name: items_repository
description: A repository that handles items related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  items_api:
    path: ../items_api
  authentication_repository:
    path: ../authentication_repository
  jellyflut_models:
    path: ../jellyflut_models
  sqlite_database:
    path: ../sqlite_database

dev_dependencies:
  pedantic: ^1.11.1
